"""Extract text from the archive's supplementary documents (BRIEF A1).

The 2021 archive ships slides (.pptx), MATLAB code (.m) and PDFs. The slides
and code are the only first-party statement of index conventions, provenance
and licensing, so their text is dumped verbatim (slide number + shape order
preserved) into docs/ucr_supplement_text.md, and a keyword pass lists every
sentence that mentions a convention/provenance/licence/scoring term with its
slide reference. PDFs are listed but not parsed (they are published papers,
secondary to the slides; parsing them is not needed for A1).
"""
from __future__ import annotations

import re
from pathlib import Path

from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE

# Terms whose surrounding sentence is worth surfacing for A2 / A5 / licence.
KEYWORDS = {
    "index": [r"\bindex", r"\b0-based", r"\b1-based", r"zero[- ]based", r"one[- ]based",
              r"\binclusive", r"\bexclusive", r"begin", r"\bend\b", r"start", r"first \d",
              r"train", r"test", r"location", r"\bwithin\b", r"\b100\b", r"plus or minus",
              r"±", r"\+/-", r"correct", r"score", r"scoring", r"grad"],
    "provenance": [r"source", r"provenance", r"from the", r"database", r"physionet",
                   r"nasa", r"dataset", r"collected", r"courtesy", r"donated", r"recorded"],
    "licence": [r"licen[cs]e", r"copyright", r"creative commons", r"cc[- ]by", r"cite",
                r"citation", r"terms", r"permission", r"free to use", r"redistribut"],
    "distorted": [r"distort", r"noise", r"synthetic", r"inject", r"inserted", r"artificial"],
}


def _shape_texts(shape) -> list[str]:
    out = []
    if shape.shape_type == MSO_SHAPE_TYPE.GROUP:
        for s in shape.shapes:
            out.extend(_shape_texts(s))
        return out
    if getattr(shape, "has_text_frame", False) and shape.has_text_frame:
        t = shape.text_frame.text.strip()
        if t:
            out.append(t)
    if getattr(shape, "has_table", False) and shape.has_table:
        for row in shape.table.rows:
            cells = [c.text.strip() for c in row.cells]
            if any(cells):
                out.append(" | ".join(cells))
    return out


def pptx_slides(path: Path) -> list[dict]:
    prs = Presentation(str(path))
    slides = []
    for i, sl in enumerate(prs.slides, 1):
        texts = []
        for sh in sl.shapes:
            texts.extend(_shape_texts(sh))
        notes = ""
        if sl.has_notes_slide:
            notes = sl.notes_slide.notes_text_frame.text.strip()
        slides.append({"n": i, "texts": texts, "notes": notes})
    return slides


def keyword_hits(doc: str, unit: str, text: str) -> list[dict]:
    hits = []
    # split into sentences / lines generously
    for sent in re.split(r"(?<=[.!?])\s+|\n+", text):
        s = sent.strip()
        if not s:
            continue
        for cat, pats in KEYWORDS.items():
            if any(re.search(p, s, re.IGNORECASE) for p in pats):
                hits.append({"doc": doc, "where": unit, "category": cat, "text": s})
                break
    return hits


def extract_all(archive_root: Path, out_md: Path) -> dict:
    """Write out_md; return {'documents': [...], 'hits': [...]}."""
    docs, hits = [], []
    lines = ["# UCR Anomaly Archive 2021 — supplementary document text",
             "",
             "GENERATED by src/data/supplement.py (called from scripts/02_audit.py). Do not hand-edit.",
             f"Source root: `{archive_root}`", ""]
    files = sorted(p for p in archive_root.rglob("*") if p.is_file()
                   and not p.name.startswith("~$") and p.name != ".DS_Store")
    for p in files:
        rel = p.relative_to(archive_root).as_posix()
        if rel.startswith("FilesAreInHere/UCR_Anomaly_FullData/"):
            continue  # the 250 series themselves
        kind = p.suffix.lower()
        docs.append({"path": rel, "bytes": p.stat().st_size, "kind": kind})
        if kind == ".pptx":
            slides = pptx_slides(p)
            lines += [f"## {rel}", f"{len(slides)} slides", ""]
            for sl in slides:
                lines.append(f"### slide {sl['n']}")
                for t in sl["texts"]:
                    lines.append(t)
                    hits += keyword_hits(rel, f"slide {sl['n']}", t)
                if sl["notes"]:
                    lines += ["", "[speaker notes]", sl["notes"]]
                    hits += keyword_hits(rel, f"slide {sl['n']} notes", sl["notes"])
                lines.append("")
        elif kind == ".m":
            text = p.read_text(errors="replace")
            lines += [f"## {rel}", "```matlab", text.rstrip(), "```", ""]
            for ln_no, ln in enumerate(text.splitlines(), 1):
                hits += keyword_hits(rel, f"line {ln_no}", ln)
        else:
            lines += [f"## {rel}", f"(binary/{kind} — listed, not parsed)", ""]
    # keyword index
    lines += ["---", "", "# Keyword index (auto-extracted sentences)", ""]
    for cat in KEYWORDS:
        lines += [f"## {cat}", ""]
        for h in hits:
            if h["category"] == cat:
                lines.append(f"- `{h['doc']}` @ {h['where']}: {h['text']}")
        lines.append("")
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text("\n".join(lines))
    return {"documents": docs, "hits": hits}
