"""04_report.py -- BRIEF Task C4: reports/gate1.md from results/gate1/*.

Reads results/gate1/detection.csv + summary.json (03_gate1.py) and the
manifest; writes reports/gate1.md. Every number in the report is computed
here (BRIEF §1-4). Gate judgement (C3): on the primary condition
(fit_on_primary, max_features_primary, buffer = window) the per-seed P1
success rate over the full 250, median over seeds, must be >= 50 %.

Exit code: 0 pass, 3 gate not met (BRIEF §7-6 STOP), 1 incomplete results.
"""
from __future__ import annotations

import csv
import json
import statistics
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.config import REPO_ROOT, load_yaml, resolve  # noqa: E402
from src.data.subsets import select  # noqa: E402

RESULTS = REPO_ROOT / "results" / "gate1"
GATE_THRESHOLD = 0.50
CRITERIA = [("p1_bw", "P1 (buffer = w)"), ("p1_b0", "P1 (buffer = 0)"),
            ("p2_archive", "P2 archive rule"), ("p2_brief", "P2 BRIEF rule")]


def md_table(header, rows):
    out = ["| " + " | ".join(map(str, header)) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def pct(x):
    return f"{100 * x:.1f}%"


def load_rows():
    with (RESULTS / "detection.csv").open() as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        r["num"] = int(r["num"])
        r["seed"] = int(r["seed"])
        # keep the CSV text: int 1 and float 1.0 are DIFFERENT models but 1 == 1.0
        # in Python, so numeric keys would silently merge the two variants
        r["max_features"] = r["max_features"]
        for k in ("p1_b0", "p1_bw", "p2_archive", "p2_brief"):
            r[k] = r[k] == "True"
        for k in ("fit_s", "score_s", "max_anom", "thr_b0", "thr_bw"):
            r[k] = float(r[k])
        r["is_medical"] = r["is_medical"]
    return rows


def rate_by_seed(rows, crit):
    """{seed: success rate over series}."""
    by = defaultdict(list)
    for r in rows:
        by[r["seed"]].append(r[crit])
    return {s: float(np.mean(v)) for s, v in sorted(by.items())}


def group_rate_by_seed(rows, crit, unit):
    """Aggregate within group (mean), then mean over groups (configs/stats.yaml)."""
    out = {}
    for seed in sorted({r["seed"] for r in rows}):
        g = defaultdict(list)
        for r in rows:
            if r["seed"] == seed:
                g[r[unit]].append(r[crit])
        out[seed] = float(np.mean([np.mean(v) for v in g.values()]))
    return out


def med(d):
    return statistics.median(d.values())


def cond_key(r):
    return (r["fit_on"], r["max_features"])


def main() -> int:
    if not (RESULTS / "detection.csv").is_file():
        raise FileNotFoundError("run scripts/03_gate1.py first")
    summary = json.loads((RESULTS / "summary.json").read_text())
    det_cfg = load_yaml("detectors")
    stats = load_yaml("stats")
    unit = stats["unit_of_analysis"]
    rows = load_rows()
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")

    n_series = len({r["num"] for r in rows})
    conds = sorted({cond_key(r) for r in rows}, key=str)
    seeds = sorted({r["seed"] for r in rows})
    complete = len(rows) == summary["expected_rows"]
    fit_p, mf_p = det_cfg["fit_on_primary"], str(det_cfg["iforest"]["max_features_primary"])
    window = int(det_cfg["iforest"]["slidingWindow"])
    primary = [r for r in rows if r["fit_on"] == fit_p and r["max_features"] == mf_p]

    L = [f"# Gate 1 — IForest detection on the UCR 2021 archive (BRIEF Task C)", "",
         f"GENERATED by scripts/04_report.py at {now}. Do not hand-edit.", "",
         f"Run `{summary['run_id']}` — `{summary['env_header']}`", "",
         md_table(["item", "value"], [
             ["series", f"{n_series} (expected {summary['n_series']})"],
             ["conditions", f"{len(conds)} (fit_on × max_features) × {len(seeds)} seeds = {len(summary['conditions'])}"],
             ["detection rows", f"{len(rows)} / {summary['expected_rows']}" + ("" if complete else " **INCOMPLETE**")],
             ["fit/score calls", f"{summary['n_calls']} — failed {summary['n_failed']} ({pct(summary['failure_rate'])})"],
             ["elapsed", f"{summary['elapsed_s']:.0f} s"],
             ["detector", f"IForest, window {window}, n_estimators {det_cfg['iforest']['n_estimators']}, normalize=False, seeds {seeds}"],
             ["unit of analysis", f"`{unit}` (configs/stats.yaml)"],
         ]), ""]

    # ---- C3 gate judgement -------------------------------------------------------
    per_seed = rate_by_seed(primary, "p1_bw")
    gate_rate = med(per_seed)
    passed = gate_rate >= GATE_THRESHOLD
    per_seed_b0 = rate_by_seed(primary, "p1_b0")
    L += ["## 1. Gate judgement (C3)", "",
          f"Pre-registered gate: P1 with buffer = window ({window}) on the full {n_series}, "
          f"`fit_on={fit_p}`, `max_features={mf_p}`, median over seeds ≥ {pct(GATE_THRESHOLD)} (D-C2-1).", "",
          md_table(["seed"] + [str(s) for s in seeds] + ["**median**"],
                   [["P1 buffer=w"] + [pct(per_seed[s]) for s in seeds] + [f"**{pct(gate_rate)}**"],
                    ["P1 buffer=0"] + [pct(per_seed_b0[s]) for s in seeds] + [pct(med(per_seed_b0))]]), "",
          f"**Result: {'PASS' if passed else 'NOT MET → STOP (BRIEF §7-6)'}** — {pct(gate_rate)} vs {pct(GATE_THRESHOLD)}.", ""]
    if not complete:
        L += ["**Results are incomplete; the judgement above is provisional.**", ""]

    # ---- 2. all conditions × criteria -----------------------------------------------
    body = []
    for fo, mf in conds:
        sub = [r for r in rows if cond_key(r) == (fo, mf)]
        line = [fo, mf]
        for crit, _ in CRITERIA:
            d = rate_by_seed(sub, crit)
            line.append(f"{pct(med(d))} [{pct(min(d.values()))}–{pct(max(d.values()))}]")
        body.append(line)
    L += ["## 2. Success rate by condition (median over seeds [min–max]; series-level, n = "
          f"{n_series})", "", md_table(["fit_on", "max_features"] + [c[1] for c in CRITERIA], body), "",
          "`max_features` int 1 = one window column per tree (benchmark default), float 1.0 = all columns "
          "(D-B2-2). The primary `max_features` is chosen on this table only.", ""]

    # group-level (aggregate within unit, then across groups)
    body = []
    for fo, mf in conds:
        sub = [r for r in rows if cond_key(r) == (fo, mf)]
        line = [fo, mf]
        for crit, _ in CRITERIA:
            d = group_rate_by_seed(sub, crit, unit)
            line.append(pct(med(d)))
        body.append(line)
    n_groups = len({r[unit] for r in rows})
    L += [f"### 2a. Same, aggregated per `{unit}` (mean within group, then mean over {n_groups} groups)", "",
          md_table(["fit_on", "max_features"] + [c[1] for c in CRITERIA], body), ""]

    # ---- 3. breakdowns on the primary condition ------------------------------------------
    def breakdown(keyfn, label):
        groups = defaultdict(list)
        for r in primary:
            groups[keyfn(r)].append(r)
        body = []
        for k, sub in sorted(groups.items(), key=lambda kv: str(kv[0])):
            n_s = len({r["num"] for r in sub})
            n_g = len({r[unit] for r in sub})
            body.append([k, n_s, n_g] + [pct(med(rate_by_seed(sub, c))) for c, _ in CRITERIA])
        return md_table([label, "n_series", f"n_{unit}s"] + [c[1] for c in CRITERIA], body)

    L += [f"## 3. Breakdowns — primary condition (`fit_on={fit_p}`, `max_features={mf_p}`), median over seeds", "",
          "### 3a. domain_goswami", "", breakdown(lambda r: r["domain_goswami"], "domain"), "",
          "### 3b. variant", "", breakdown(lambda r: r["variant"], "variant"), "",
          "### 3c. is_medical", "", breakdown(lambda r: r["is_medical"], "is_medical"), ""]
    subsets_cfg = load_yaml("subsets")["subsets"]
    body = []
    for name in ("all", "non_medical", "physical", "plain_only", "no_sentinel"):
        nums = {int(r["num"]) for r in select(_manifest(), [name], subsets_cfg)}
        sub = [r for r in primary if r["num"] in nums]
        if not sub:
            body.append([name, 0, 0] + ["NA"] * len(CRITERIA))
            continue
        body.append([name, len(nums), len({r[unit] for r in sub})] + [pct(med(rate_by_seed(sub, c))) for c, _ in CRITERIA])
    L += ["### 3d. Subsets (configs/subsets.yaml; descriptive — D-F2-2)", "",
          md_table(["subset", "n_series", f"n_{unit}s"] + [c[1] for c in CRITERIA], body), ""]

    # ---- 4. seed variance --------------------------------------------------------------------
    L += ["## 4. Seed variance (primary condition)", ""]
    body = []
    for crit, label in CRITERIA:
        by_num = defaultdict(list)
        for r in primary:
            by_num[r["num"]].append(r[crit])
        agree_t = sum(1 for v in by_num.values() if all(v))
        agree_f = sum(1 for v in by_num.values() if not any(v))
        mixed = len(by_num) - agree_t - agree_f
        body.append([label, agree_t, agree_f, mixed])
    L += [md_table(["criterion", "all seeds detect", "no seed detects", "seeds disagree"], body), ""]

    # ---- 5. fit_on and max_features effects (paired per series × seed) -------------------------
    def paired(keyA, keyB, field, crit="p1_bw"):
        a = {(r["num"], r["seed"]): r[crit] for r in rows if r[field] == keyA and
             (r["max_features"] == mf_p if field == "fit_on" else r["fit_on"] == fit_p)}
        b = {(r["num"], r["seed"]): r[crit] for r in rows if r[field] == keyB and
             (r["max_features"] == mf_p if field == "fit_on" else r["fit_on"] == fit_p)}
        keys = sorted(set(a) & set(b))
        both = sum(1 for k in keys if a[k] and b[k])
        only_a = sum(1 for k in keys if a[k] and not b[k])
        only_b = sum(1 for k in keys if b[k] and not a[k])
        neither = len(keys) - both - only_a - only_b
        return [f"{keyA!r} vs {keyB!r}", len(keys), both, only_a, only_b, neither]
    fos = det_cfg["fit_on_variants"]
    mfs = [str(m) for m in det_cfg["iforest"]["max_features_variants"]]
    L += ["## 5. Paired comparisons on P1 (buffer = w), series × seed pairs", "",
          md_table(["comparison", "pairs", "both detect", "only first", "only second", "neither"], [
              paired(fos[0], fos[1], "fit_on"),
              paired(mfs[0], mfs[1], "max_features"),
          ]), "",
          f"fit_on comparison at `max_features={mf_p}`; max_features comparison at `fit_on={fit_p}`.", ""]

    # ---- 6. runtime ----------------------------------------------------------------------------
    fit_s = [r["fit_s"] for r in rows]
    sc_s = [r["score_s"] for r in rows]
    L += ["## 6. Runtime", "",
          md_table(["phase", "n", "median s", "max s", "total s"], [
              ["fit", len(fit_s), f"{np.median(fit_s):.2f}", f"{max(fit_s):.1f}", f"{sum(fit_s):.0f}"],
              ["score", len(sc_s), f"{np.median(sc_s):.2f}", f"{max(sc_s):.1f}", f"{sum(sc_s):.0f}"]]), ""]

    # ---- 7. failures -----------------------------------------------------------------------------
    fail_path = REPO_ROOT / "runs" / summary["run_id"] / "failures.jsonl"
    fails = [json.loads(l) for l in fail_path.read_text().splitlines()] if fail_path.is_file() else []
    L += ["## 7. Failures", "", f"{len(fails)} failed calls (`runs/{summary['run_id']}/failures.jsonl`)", ""]
    L += [f"- {f['series_num']:03d} {f['phase']} fit_on={f['fit_on']} seed={f['seed']} "
          f"mf={f['config'].get('max_features')}: {f['error']}" for f in fails]
    L += ["", "## 8. Pre-registration record (C2)", "",
          "- P1: `max(score[start0:stop0]) > percentile(score[normal_test], 99)`; normal_test = test region "
          "minus anomaly ± buffer; buffer ∈ {0, window}; gate uses buffer = window (D-C2-1).",
          "- P2 archive rule: `min(begin−L, begin−100) < P < max(end+L, end+100)` in the archive's 1-based "
          "frame (UCR_AnomalyDataSets.pptx slide 4; Irrational Exuberance.pptx slide 64) — evidence found, "
          "so BRIEF's \"근거 미확인\" caveat does not apply; BRIEF's `[start0−100, stop0+100)` is reported alongside.",
          "- Scores: raw `decision_function` output, no MinMax scaling (docs/TSBAD_INTERNALS.md §4).",
          "- Success rates are series-level; group-level aggregation follows configs/stats.yaml.", ""]

    out = resolve(load_yaml("paths")["reports_dir"]) / "gate1.md"
    out.write_text("\n".join(L))
    print(f"wrote {out}: gate {'PASS' if passed else 'NOT MET'} ({pct(gate_rate)})")
    if not complete:
        return 1
    return 0 if passed else 3


def _manifest():
    with resolve(load_yaml("paths")["manifest"]).open() as f:
        return list(csv.DictReader(f))


if __name__ == "__main__":
    sys.exit(main())
