"""w2_e2_report.py -- reports/w2_artifact.md and reports/figures/w2/ai_by_operator.png from E2 outputs.

Reads results/w2/ai.csv.gz, sar.csv.gz, e2_summary.json (scripts/w2_e2.py). Every number is computed
here (CLAUDE.md §1-4). Unit of analysis = content_group; the sample has one series per group, so a
group statistic is that series' statistic. Primary summaries are medians ACROSS SERIES of per-series
medians (group level); pooled region-level medians are shown alongside. AI keeps its sign (D9).

Flagged series (D-E2-2): positions_short at some length, a length dropped (< 10 positions),
sar_few_positions, SAR-excluded (< 5 positions), sar_den_zero for a non-identity operator, or any
no-donor region. Main tables are given with and without them.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.config import REPO_ROOT  # noqa: E402

RES = REPO_ROOT / "results" / "w2"
REPORT = REPO_ROOT / "reports" / "w2_artifact.md"
FIG = REPO_ROOT / "reports" / "figures" / "w2" / "ai_by_operator.png"
OPS = ["B1_zero", "B2_global_mean", "B3_local_mean", "B4_linear_interp", "B5_gaussian", "B6_shuffle",
       "recon_test", "recon_train", "identity"]
LENS = ["0.25", "0.5", "1.0"]


def md_table(header, rows):
    out = ["| " + " | ".join(map(str, header)) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def f(v, p=3):
    if v is None or (isinstance(v, float) and not np.isfinite(v)):
        return "—"
    a = abs(v)
    return f"{v:.{p}g}" if (a != 0 and (a < 1e-3 or a >= 1e4)) else f"{v:.{p}f}"


def flags(ai: pd.DataFrame, sar: pd.DataFrame, summ: dict) -> pd.DataFrame:
    rows = []
    for num, info in summ["positions"].items():
        num = int(num)
        short = [k for k, v in info.items() if k != "GT" and 10 <= v["placed"] < 20]
        dropped = [k for k, v in info.items() if k != "GT" and v["placed"] < 10]
        s = sar[(sar.series_id == num) & (sar.op != "identity")]
        nd = ai[(ai.series_id == num) & ai.no_donor]
        rows.append({"series_id": num, "positions_short": ",".join(short), "length_dropped": ",".join(dropped),
                     "sar_few_positions": bool(info["GT"]["placed"] < 10), "sar_excluded": bool(info["GT"]["placed"] < 5),
                     "sar_den_zero_ops": ",".join(sorted(s[s.sar_den_zero].op)), "no_donor_regions": int(len(nd))})
    fl = pd.DataFrame(rows)
    fl["flagged"] = ((fl.positions_short != "") | (fl.length_dropped != "") | fl.sar_few_positions
                     | fl.sar_excluded | (fl.sar_den_zero_ops != "") | (fl.no_donor_regions > 0))
    return fl


def per_series_median(d: pd.DataFrame, by=("op",)) -> pd.DataFrame:
    return d.groupby(["series_id", *by]).AI.median().reset_index()


def main() -> int:
    ai = pd.read_csv(RES / "ai.csv.gz", dtype={"L_rel": str})
    sar = pd.read_csv(RES / "sar.csv.gz")
    summ = json.loads((RES / "e2_summary.json").read_text())
    fl = flags(ai, sar, summ)
    flagged = set(fl[fl.flagged].series_id)
    L = []
    A = L.append
    A("# W2 E2 — Artifact Index and SAR (C1)\n")
    A(f"GENERATED by scripts/w2_e2_report.py at {datetime.now(timezone.utc).isoformat(timespec='seconds')} from "
      f"`results/w2/` (scripts/w2_e2.py run at {summ['generated_utc']}, HEAD `{summ['head'][:7]}`). "
      "Do not hand-edit.\n")
    A(f"`{summ['env_header']}`\n")
    A(md_table(["item", "value"], [
        ["decision commit (rev1 §3)", f"`{summ['decision_commit'][:7]}` at {summ['decision_time']}"],
        ["sample", f"{summ['n_series']} series = 89 content_groups, one each (rev1 §5; DECISIONS 표본)"],
        ["rows (region × operator)", f"{summ['n_rows']:,}"],
        ["run time", f"{summ['elapsed_s']:.0f} s (4 workers × 2 numba threads)"],
        ["AI", "(resp(x′, R) − resp(x, R)) / scale(x); resp = max over J(R) of score_patch; sign kept (D7–D9)"],
        ["unit of analysis", "content_group (= series here); primary = median across series of per-series medians"],
        ["STOP (rev1 §11)", "; ".join(summ["stops"]) if summ["stops"] else "none"],
    ]))
    A("")

    # exclusions and flags
    A("## 1. Exclusions and flags\n")
    nd = summ["no_donor"]
    A(md_table(["item", "count"], [
        ["scale(x) invalid (series excluded)", len(summ["scale_excluded"])],
        ["positions_short (10–19 placed at some length)", int((fl.positions_short != "").sum())],
        ["length dropped (< 10 placed; D-E2a-1)", int((fl.length_dropped != "").sum())],
        ["sar_few_positions (< 10)", int(fl.sar_few_positions.sum())],
        ["SAR-excluded (< 5)", int(fl.sar_excluded.sum())],
        ["sar_den_zero (non-identity operator)", int((fl.sar_den_zero_ops != "").sum())],
        *[[f"no donor: {op}", f"{v['n']}/{v['of']} regions"] for op, v in nd.items()],
        ["**flagged series (any of the above)**", len(flagged)],
    ]))
    det = fl[fl.flagged]
    if len(det):
        A("\n" + md_table(["series", "positions_short", "length dropped", "sar_few", "sar_excl", "sar_den_zero ops",
                           "no-donor regions"],
                          [[int(r.series_id), r.positions_short or "—", r.length_dropped or "—",
                            "yes" if r.sar_few_positions else "", "yes" if r.sar_excluded else "",
                            r.sar_den_zero_ops or "—", r.no_donor_regions] for r in det.itertuples()]))
    A("")

    # AI by operator
    A("## 2. Artifact Index on normal regions, by operator (signed)\n")
    nrm = ai[(ai.region == "normal") & ~ai.no_donor]
    for tag, d in (("all 89 series", nrm), (f"flagged series removed ({89 - len(flagged)} series)",
                                              nrm[~nrm.series_id.isin(flagged)])):
        ps = per_series_median(d, by=("op", "L_rel"))
        rows = []
        for op in OPS:
            r = [op]
            for lr in LENS:
                v = ps[(ps.op == op) & (ps.L_rel == lr)].AI
                r.append(f"{f(v.median())} [{f(v.quantile(.25))}, {f(v.quantile(.75))}]" if len(v) else "—")
            pooled = d[d.op == op].AI
            r += [f(pooled.median()), f(float((pooled > 0).mean() * 100), 3) + "%"]
            rows.append(r)
        A(f"**{tag}** — median across series of per-series median AI [IQR across series]; pooled region median; "
          "share of regions with AI > 0\n")
        A(md_table(["operator", "|R| = 0.25w", "0.5w", "1.0w", "pooled median", "AI > 0"], rows))
        A("")

    # D12
    A("## 3. D12 predictions (approved; tol 1e-12 for a/a′, 1e-3 for b)\n")
    eq = ai[(ai.L == ai.w) & ~ai.no_donor].copy()
    eq["root"] = np.sqrt(eq.w.astype(float))
    checks = {
        "D12-a (i) s(j*)_after = √w": (eq[(eq.canonical_shape == "constant") & (eq.n_const_train == 0)],
                                        lambda d: (d.s_jstar_after - d.root).abs() <= 1e-12),
        "D12-a (ii) resp_after ≥ √w − tol": (eq[(eq.canonical_shape == "constant") & (eq.n_const_train == 0)],
                                             lambda d: d.resp_after >= d.root - 1e-12),
        "D12-a′ s(j*)_after = 0": (eq[(eq.canonical_shape == "constant") & (eq.n_const_train > 0)],
                                   lambda d: d.s_jstar_after.abs() <= 1e-12),
        "D12-b s(j*)_after ≤ 1e-3 (recon_train)": (eq[eq.op == "recon_train"], lambda d: d.s_jstar_after <= 1e-3),
    }
    rows, mism = [], []
    for name, (d, fn) in checks.items():
        ok = fn(d)
        by_region = ", ".join(f"{k} {int(v)}" for k, v in d.region.value_counts().sort_index().items())
        rows.append([name, len(d), int(ok.sum()), f"{100 * ok.mean():.2f}%" if len(d) else "—",
                     int((~ok).sum()), "STOP" if len(d) and (~ok).mean() > 0.01 else "ok", by_region or "—"])
        for r in d[~ok].itertuples():
            mism.append([name, int(r.series_id), r.op, r.region, f"[{r.a}, {r.b})", int(r.w), int(r.n_const_train),
                         f(r.s_jstar_after, 6), f(r.resp_after, 6), f(r.root, 6)])
    A(md_table(["prediction", "cases", "match", "match rate", "mismatch", "> 1%?", "cases by region"], rows))
    A("")
    b = checks["D12-b s(j*)_after ≤ 1e-3 (recon_train)"][0].s_jstar_after
    A(f"**D12-b residual distribution** (s(j*)_after for recon_train, |R| = w; n = {len(b)}): max {f(b.max(), 4)}, "
      f"99% quantile {f(b.quantile(.99), 4)}, median {f(b.median(), 4)}, exactly 0: {int((b == 0).sum())}.\n")
    if mism:
        A("Mismatches:\n")
        A(md_table(["prediction", "series", "operator", "region", "R", "w", "n_const_train", "s(j*)_after",
                    "resp_after", "√w"], mism[:200]))
        if len(mism) > 200:
            A(f"\n({len(mism) - 200} more in results/w2/ai.csv.gz)")
    A("")

    # SAR
    A("## 4. SAR (D10) and SAR_abs, by operator\n")
    for tag, s in (("all 89 series", sar), (f"flagged series removed", sar[~sar.series_id.isin(flagged)])):
        rows = []
        for op in OPS:
            d = s[s.op == op]
            v, va = d.SAR.dropna(), d.SAR_abs.dropna()
            rows.append([op, len(v), f(v.median()), f"[{f(v.quantile(.25))}, {f(v.quantile(.75))}]",
                         f(va.median()), f"[{f(va.quantile(.25))}, {f(va.quantile(.75))}]",
                         f"{100 * d.reversal.mean():.1f}%", f(d.AI_anom.median()), int(d.sar_den_zero.sum())])
        A(f"**{tag}** — median across series [IQR]; reversal = AI_anom > 0\n")
        A(md_table(["operator", "series with SAR", "SAR median", "SAR IQR", "SAR_abs median", "SAR_abs IQR",
                    "reversal", "AI_anom median", "sar_den_zero"], rows))
        A("")
    A("`identity` has AI ≡ 0 by construction (gate 2), so its SAR denominator is 0 (`sar_den_zero`).\n")

    # splits
    A("## 5. Splits (normal regions, per-series median AI; median across series)\n")
    ps = per_series_median(nrm, by=("op",)).merge(ai[["series_id", "detected", "domain"]].drop_duplicates(), on="series_id")
    A(md_table(["operator", "detected", "not detected"],
               [[op, f(ps[(ps.op == op) & ps.detected].AI.median()), f(ps[(ps.op == op) & ~ps.detected].AI.median())]
                for op in OPS]))
    A(f"\nSeries: detected {int(ps.drop_duplicates('series_id').detected.sum())}, not detected "
      f"{int((~ps.drop_duplicates('series_id').detected).sum())}.\n")
    doms = sorted(ps.domain.unique())
    A(md_table(["operator", *[f"{d} (n={ps[ps.domain == d].series_id.nunique()})" for d in doms]],
               [[op, *[f(ps[(ps.op == op) & (ps.domain == d)].AI.median()) for d in doms]] for op in OPS]))
    A("")

    # recon contrast
    A("## 6. recon_test vs recon_train (D11 contrast; recon_train is not used for conclusions)\n")
    pr = ai[ai.op.isin(["recon_test", "recon_train"]) & ~ai.no_donor].pivot_table(
        index=["series_id", "region", "L_rel", "pos_idx"], columns="op", values="AI").dropna()
    rows = []
    for (reg, lr), g in pr.groupby(level=[1, 2]):
        dlt = g.recon_train - g.recon_test
        rows.append([reg, lr, len(g), f(g.recon_test.median()), f(g.recon_train.median()), f(dlt.median()),
                     f"{100 * (g.recon_train < g.recon_test).mean():.1f}%"])
    A(md_table(["region", "|R|", "paired regions", "recon_test median AI", "recon_train median AI",
                "median (train − test)", "train < test"], rows))
    A("")
    st = sar[sar.op.isin(["recon_test", "recon_train"])].pivot_table(index="series_id", columns="op", values="SAR")
    A(f"SAR median: recon_test {f(st.recon_test.median())}, recon_train {f(st.recon_train.median())} "
      f"(series with both: {int(st.dropna().shape[0])}).\n")

    # figure
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    FIG.parent.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(1, 3, figsize=(14, 5.2), sharey=True, constrained_layout=True)
    for ax, lr in zip(axes, LENS):
        ps_l = per_series_median(nrm[nrm.L_rel == lr])
        data = [ps_l[ps_l.op == op].AI.to_numpy() for op in OPS]
        ax.boxplot(data, orientation="horizontal", tick_labels=OPS, showfliers=True, widths=0.6,
                   medianprops=dict(color="#0072B2", lw=2), flierprops=dict(marker=".", ms=3, mec="0.5"),
                   boxprops=dict(color="0.3"), whiskerprops=dict(color="0.3"), capprops=dict(color="0.3"))
        ax.axvline(0, color="0.6", lw=0.8, ls=":")
        ax.set_xscale("symlog", linthresh=0.1)
        ax.set_title(f"|R| = {lr}w")
        ax.set_xlabel("per-series median AI (symlog)")
        ax.invert_yaxis()
        ax.grid(axis="x", color="0.92")
    fig.suptitle("W2 E2 — Artifact Index on normal regions by operator (89 series; sign kept)")
    fig.savefig(FIG, dpi=200)
    plt.close(fig)
    A("## 7. Figure\n")
    A(f"- `{FIG.relative_to(REPO_ROOT)}` — per-series median AI on normal regions, by operator and |R|.\n")
    REPORT.write_text("\n".join(L) + "\n")
    print(f"wrote {REPORT} and {FIG}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
