"""w2_e3v2_report.py -- reports/w2_ranking.md (MAIN E3 result, D-E3-5 random-tie version) and
reports/figures/w2/rank_bump.png.

Inputs: results/w2/faithfulness_v2.csv.gz, e3v2_ties.csv, e3v2_series.csv, e3v2_run.json (scripts/w2_e3_curves.py),
and, for the side-by-side comparison only, the index-tie version results/w2/faithfulness.csv.gz (규칙 확정 전 버전,
reports/w2_ranking_v1_index_ties.md). Ranking metric, aggregation, bootstrap: as scripts/w2_e3_report.py
(Šimić CMI(mean DDS, PES) per (operator, AM); ties in CMI -> average rank; content_group bootstrap B = 1000).
No interpretation is written (researcher instruction, DECISIONS "보고 추가 요구").
"""
from __future__ import annotations

import itertools
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import rankdata, spearmanr, wilcoxon

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from src.config import REPO_ROOT  # noqa: E402
from src.metrics.faithfulness_simic import cmi, pes  # noqa: E402
from w2_e3_report import AMS, B, EVAL_OPS, SEED, cmi_table, f, holm, kendall_w, md_table, pair_rhos, ranks  # noqa: E402

RES = REPO_ROOT / "results" / "w2"
REPORT = REPO_ROOT / "reports" / "w2_ranking.md"
FIG = REPO_ROOT / "reports" / "figures" / "w2" / "rank_bump.png"


def analysis(fz: pd.DataFrame, condition: str = "main") -> dict:
    d = fz[fz.condition == condition].pivot_table(index="series_id", columns=["eval_op", "am"], values="dds")
    c = cmi_table(d).loc[EVAL_OPS, AMS]
    rk = ranks(c)
    return {"dds": d, "cmi": c, "rk": rk, "W": kendall_w(rk.to_numpy()), "rhos": pair_rhos(rk)}


def bootstrap(dds: pd.DataFrame) -> tuple[list, dict]:
    rng = np.random.default_rng(SEED)
    ids = dds.index.to_numpy()
    bw, br = [], {}
    for _ in range(B):
        rkb = ranks(cmi_table(dds.loc[rng.choice(ids, size=ids.size, replace=True)]).loc[EVAL_OPS, AMS])
        bw.append(kendall_w(rkb.to_numpy()))
        for k, v in pair_rhos(rkb).items():
            br.setdefault(k, []).append(v)
    return bw, br


def ci(v) -> str:
    v = np.asarray(v, dtype=float)
    if not np.isfinite(v).any():
        return "[—, —]"
    return f"[{f(np.nanpercentile(v, 2.5))}, {f(np.nanpercentile(v, 97.5))}]"


def rank_with(d_main: pd.DataFrame, override: dict, op: str) -> tuple[pd.Series, np.ndarray]:
    """CMI per AM under `op`, with some AMs' DDS columns replaced (sensitivity conditions)."""
    cols = {a: override.get(a, d_main[(op, a)]) for a in AMS}
    cs = pd.Series({a: cmi(float(v.dropna().mean()), pes(v.dropna().to_numpy())) for a, v in cols.items()})[AMS]
    return cs, rankdata(-cs.to_numpy())


def main() -> int:
    v2 = pd.read_csv(RES / "faithfulness_v2.csv.gz")
    v1 = pd.read_csv(RES / "faithfulness.csv.gz")
    ties = pd.read_csv(RES / "e3v2_ties.csv")
    info = pd.read_csv(RES / "e3v2_series.csv")
    run = json.loads((RES / "e3v2_run.json").read_text())
    run1 = json.loads((RES / "e3_run.json").read_text())
    A2, A1 = analysis(v2), analysis(v1)
    bw, br = bootstrap(A2["dds"])
    L = []
    A = L.append
    A("# W2 E3 — AM ranking under different evaluation operators (C2) — MAIN RESULT (D-E3-5)\n")
    A(f"GENERATED by scripts/w2_e3v2_report.py at {datetime.now(timezone.utc).isoformat(timespec='seconds')} from "
      f"`results/w2/faithfulness_v2.csv.gz` (scripts/w2_e3_curves.py run at {run['generated_utc']}, HEAD "
      f"`{run['head'][:7]}`). Do not hand-edit. Classification already showed evaluation-operator dependence "
      "(Šimić et al. 2025); this is the AD check, no novelty is claimed. No interpretation is given.\n")
    A(f"`{run['env_header']}`\n")
    A(md_table(["item", "value"], [
        ["decision commits", f"`{run['decision_commit'][:7]}` (D10–D13), `{run['decision_commit_2'][:7]}` (D-E3-5, D-E4-1/2/3)"],
        ["version", "**random seeded ties** (seed = series, AM); LeRF = exact reverse of MoRF (D-E3-5). "
                    "The index-tie version (규칙 확정 전 버전) is `reports/w2_ranking_v1_index_ties.md`."],
        ["attributions", f"reused from the E3 run of {run1['generated_utc']} (`results/w2/e3_attr.csv.gz`); only curves recomputed"],
        ["check", run["tie_free_check"]],
        ["series", f"{run['n_series']} (one per content_group)"],
        ["evaluation operators (main)", ", ".join(EVAL_OPS) + "; recon_train separate; identity excluded"],
        ["ranking metric", "CMI(mean DDS, PES) per (operator, AM) (Šimić trace); ties in CMI → average rank"],
        ["curve recomputation time", f"{run['elapsed_s'] / 60:.1f} min"],
    ]))
    A("")
    c, rk, dds = A2["cmi"], A2["rk"], A2["dds"]
    A("## 1. Main analysis: CMI and AM ranks per evaluation operator\n")
    A(md_table(["operator", *[f"{a} CMI" for a in AMS], *[f"{a} rank" for a in AMS]],
               [[op, *[f(c.loc[op, a]) for a in AMS], *[f(rk.loc[op, a], 2) for a in AMS]] for op in EVAL_OPS]))
    A("\nMean DDS / PES per (operator, AM):\n")
    A(md_table(["operator", *AMS], [[op, *[f"{f(dds[(op, a)].mean())} / {f(pes(dds[(op, a)].dropna().to_numpy()))}"
                                           for a in AMS]] for op in EVAL_OPS]))
    A("")
    A("## 2. Agreement between operators\n")
    A(f"**Kendall's W over the 6 operators: {f(A2['W'])}** (bootstrap 95 % CI {ci(bw)}, B = {B}, resampling "
      "content_groups).\n")
    A(md_table(["operator pair", "Spearman ρ", "95 % CI"],
               [[f"{a} – {b}", f(v), ci(br[(a, b)])] for (a, b), v in A2["rhos"].items()]))
    A("\n**Resolution limit:** with 4 AMs a Spearman ρ can take only 11 values (−1, −0.8, …, 1 without ties).\n")
    pg = []
    main = v2[v2.condition == "main"]
    for _, g in main.groupby("series_id"):
        t = g.pivot_table(index="eval_op", columns="am", values="dds").reindex(index=EVAL_OPS, columns=AMS)
        if not t.isna().any().any():
            pg.append(kendall_w(np.vstack([rankdata(-t.loc[op].to_numpy()) for op in EVAL_OPS])))
    pg = np.array(pg)
    A(f"**Secondary — per-group W** (AMs ranked by DDS per series): n = {pg.size}, median {f(np.median(pg))}, "
      f"IQR [{f(np.quantile(pg, .25))}, {f(np.quantile(pg, .75))}].\n")
    A("**Secondary — AM pairs per operator** (Wilcoxon signed-rank on per-series DDS, Holm within operator):\n")
    rows = []
    for op in EVAL_OPS:
        pairs = list(itertools.combinations(AMS, 2))
        ps, meds = [], []
        for a, b in pairs:
            dd = (dds[(op, a)] - dds[(op, b)]).dropna()
            ps.append(float(wilcoxon(dd).pvalue) if (dd != 0).any() else 1.0)
            meds.append(float(dd.median()))
        rows += [[op, f"{a} − {b}", f(m), f(p), f(pa)] for (a, b), p, pa, m in zip(pairs, ps, holm(ps), meds)]
    A(md_table(["operator", "pair (DDS difference)", "median difference", "p", "Holm p"], rows))
    A("")
    A("## 3. Self-agreement sensitivity (explanation operator = evaluation operator)\n")
    sf = v2[v2.condition == "self"]
    rows = []
    for op in EVAL_OPS:
        ov = {am: sf[(sf.eval_op == op) & (sf.am == am)].set_index("series_id").dds.reindex(dds.index)
              for am in ("FeatureAblation", "KernelSHAP")}
        _, rs = rank_with(dds, ov, op)
        rm = rk.loc[op].to_numpy()
        rho = float(spearmanr(rm, rs).statistic) if np.ptp(rm) > 0 and np.ptp(rs) > 0 else np.nan
        rows.append([op, *[f"{f(rm[i], 2)} → {f(rs[i], 2)}" for i in range(4)], f(rho)])
    A(md_table(["operator", *[f"{a} rank (main → self)" for a in AMS], "ρ(main, self)"], rows))
    A("")
    A("## 4. |R| ordering sensitivity (D-E3-5; FeatureAblation and KernelSHAP only)\n")
    ab = v2[v2.condition == "abs"]
    rows = []
    for op in EVAL_OPS:
        ov = {am: ab[(ab.eval_op == op) & (ab.am == am)].set_index("series_id").dds.reindex(dds.index)
              for am in ("FeatureAblation", "KernelSHAP")}
        _, rs = rank_with(dds, ov, op)
        rm = rk.loc[op].to_numpy()
        rho = float(spearmanr(rm, rs).statistic) if np.ptp(rm) > 0 and np.ptp(rs) > 0 else np.nan
        rows.append([op, *[f"{f(rm[i], 2)} → {f(rs[i], 2)}" for i in range(4)], f(rho)])
    A(md_table(["operator", *[f"{a} rank (signed → |R|)" for a in AMS], "ρ(signed, |R|)"], rows))
    A("\nRandom and MPNative are non-negative, so their order is the same under |R|; only ranks can move.\n")
    sep = v2[v2.condition == "separate"]
    if len(sep):
        ds = sep.pivot_table(index="series_id", columns="am", values="dds")
        cs = pd.Series({a: cmi(float(ds[a].dropna().mean()), pes(ds[a].dropna().to_numpy())) for a in AMS})
        A("## 5. recon_train as evaluation operator (separate)\n")
        A(md_table(["AM", "CMI", "rank"], [[a, f(cs[a]), f(r, 2)] for a, r in zip(AMS, rankdata(-cs.to_numpy()))]))
        A("")
    A("## 6. Random-tie version vs index-tie version (규칙 확정 전 버전)\n")
    A("AM ranks per operator, side by side (v2 = random ties, main; v1 = index ties):\n")
    A(md_table(["operator", *[f"{a} v2 / v1" for a in AMS]],
               [[op, *[f"{f(rk.loc[op, a], 2)} / {f(A1['rk'].loc[op, a], 2)}" for a in AMS]] for op in EVAL_OPS]))
    A("\nCMI per (operator, AM), v2 / v1:\n")
    A(md_table(["operator", *AMS], [[op, *[f"{f(c.loc[op, a])} / {f(A1['cmi'].loc[op, a])}" for a in AMS]]
                                    for op in EVAL_OPS]))
    A(f"\n**Kendall's W:** v2 {f(A2['W'])}, v1 {f(A1['W'])}.\n")
    A(md_table(["operator pair", "ρ v2", "ρ v1"], [[f"{a} – {b}", f(A2["rhos"][(a, b)]), f(A1["rhos"][(a, b)])]
                                                   for (a, b) in A2["rhos"]]))
    A("")
    A("## 7. Tie diagnostics (tied segments / K, per explanation)\n")
    ties["ratio"] = ties.tied_segments / ties.K
    rows = []
    for (cond, am), g in ties.groupby(["condition", "am"]):
        rows.append([cond, am, len(g), f"{100 * (g.tied_segments > 0).mean():.1f}%", f(g.ratio.median()),
                     f"[{f(g.ratio.quantile(.25))}, {f(g.ratio.quantile(.75))}]", f(g.ratio.max())])
    A(md_table(["condition", "AM", "explanations", "with ties", "median ratio", "IQR", "max"], rows))
    A("")
    b3r, b3o = int(info.b3_runs.sum()), int(info.b3_overlap.sum())
    A("## 8. Limits\n")
    A(f"- **B3 context overlap (D-E1-2):** of {b3r:,} B3 run applications in this recomputation, {b3o:,} "
      f"({100 * b3o / max(b3r, 1):.1f}%) had their 50-point context overlap another masked run.\n"
      "- DDS is not bounded to [−1, 1] (curves are anomaly scores; max_diff = scale(x), D8).\n")
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    colors = {"Random": "#999999", "FeatureAblation": "#0072B2", "KernelSHAP": "#D55E00", "MPNative": "#009E73"}
    marks = {"Random": "o", "FeatureAblation": "s", "KernelSHAP": "^", "MPNative": "D"}
    fig, ax = plt.subplots(figsize=(10, 4.8), constrained_layout=True)
    xs = np.arange(len(EVAL_OPS))
    for a in AMS:
        ax.plot(xs, rk[a].to_numpy(), marker=marks[a], color=colors[a], lw=2, ms=8, label=a)
        ax.annotate(a, (xs[-1] + 0.08, rk[a].iloc[-1]), va="center", fontsize=10, color="0.2")
    ax.set_xticks(xs, EVAL_OPS, rotation=15)
    ax.set_yticks([1, 2, 3, 4])
    ax.set_ylim(4.5, 0.5)
    ax.set_xlim(-0.3, len(EVAL_OPS) - 0.3 + 0.9)
    ax.set_ylabel("AM rank by CMI (1 = best)")
    ax.set_title(f"W2 E3 (random ties, D-E3-5) — AM ranking per evaluation operator (89 series; W = {A2['W']:.2f})")
    ax.grid(axis="y", color="0.92")
    ax.legend(loc="lower left", frameon=False, ncol=4)
    fig.savefig(FIG, dpi=200)
    plt.close(fig)
    A("## 9. Figure\n")
    A(f"- `{FIG.relative_to(REPO_ROOT)}` (index-tie version: `reports/figures/w2/rank_bump_v1_index_ties.png`)\n")
    REPORT.write_text("\n".join(L) + "\n")
    print(f"wrote {REPORT} and {FIG}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
